# tool_mapping.yml

ftp:
  ports: [21, 990]
  scripts:
    - ftp_enum.py
  advanced_logic:
    # Example of condition-based logic. (Optional)
    # If you detect SSL or TLS on port 990, you might run a specialized script.
    - condition: "ssl_detected_on_990"
      scripts:
        - ftps_enum.py

ssh:
  ports: [22]
  scripts:
    - ssh_enum.py

http:
  ports: [80, 443, 8080, 8443]
  scripts:
    - http_enum.py
  advanced_logic:
    - condition: "banner_contains('IIS')"
      scripts:
        - iis_enum.py
    - condition: "banner_contains('Apache')"
      scripts:
        - apache_enum.py
    - condition: "banner_contains('nginx')"
      scripts:
        - nginx_enum.py

smb:
  ports: [139, 445]
  scripts:
    - smb_enum.py

rdp:
  ports: [3389]
  scripts:
    - rdp_enum.py

mysql:
  ports: [3306]
  scripts:
    - mysql_enum.py

mssql:
  ports: [1433]
  scripts:
    - mssql_enum.py

winrm:
  ports: [5985, 5986]
  scripts:
    - winrm_enum.py

snmp:
  ports: [161]
  scripts:
    - snmp_enum.py

telnet:
  ports: [23]
  scripts:
    - telnet_enum.py

oracle:
  ports: [1521]
  scripts:
    - oracle_enum.py

postgres:
  ports: [5432]
  scripts:
    - postgres_enum.py

vnc:
  ports: [5900, 5901, 5902, 5903]
  scripts:
    - vnc_enum.py

redis:
  ports: [6379]
  scripts:
    - redis_enum.py

citrix:
  ports: [1494, 2598, 443]
  scripts:
    - citrix_enum.py

elasticsearch:
  ports: [9200, 9300]
  scripts:
    - es_enum.py

# --- New or Additional Services/Ports Below ---

smtp:
  ports: [25, 465, 587]
  scripts:
    - smtp_enum.py
  advanced_logic:
    - condition: "banner_contains('Exchange')"
      scripts:
        - exchange_enum.py

pop3:
  ports: [110, 995]
  scripts:
    - pop3_enum.py

imap:
  ports: [143, 993]
  scripts:
    - imap_enum.py

ldap:
  ports: [389, 636]
  scripts:
    - ldap_enum.py
  advanced_logic:
    - condition: "ssl_detected_on_636"
      scripts:
        - ldaps_enum.py

nfs:
  ports: [111, 2049]
  scripts:
    - nfs_enum.py

docker:
  ports: [2375, 2376]
  scripts:
    - docker_enum.py

kubernetes:
  ports: [10250, 10255]
  scripts:
    - kube_enum.py

rpcbind:
  ports: [111]
  scripts:
    - rpc_enum.py

rdp_gateway:
  ports: [3389, 3391]  # Some RDP gateway services
  scripts:
    - rdp_enum.py
    - rdp_gateway_enum.py

# Additional placeholders for advanced logic can be added as needed
